---
- name: Disable SELinux
  selinux:
    state: disabled

- name: Disable firewalld
  service:
    name: firewalld
    enabled: false
  register: firewalld_service_result
  failed_when: "firewalld_service_result is failed and 'Could not find the requested service' not in firewalld_service_result.msg"  

# Download software
# - name: Download JDK 8

- name: Copy JDK 8, Elasticsearch and Kibana rpms.
  copy:
    src: "{{ item }}"
    dest: /root/
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - src/elasticsearch/*  

# Install RPM 
- name: Install Java 8 from local file
  yum: name=/root/jdk-8u201-linux-x64.rpm 

- name: Install Elasticsearch
  yum: name=/root/elasticsearch-5.6.14.rpm

- name: Update elasticsearch.service
  copy:
    src: roles/es-data/files/system/elasticsearch.service
    dest: /usr/lib/systemd/system/elasticsearch.service
    owner: root
    group: root
    mode: 0644

- name: Install Elasticsearch Plugins
  elasticsearch_plugin: name={{ item.name }} state={{ item.state }} src={{ item.src }} force={{ item.force }}
  with_items:
    - { name: 'x-pack', state: 'present', src: 'file:///root/x-pack-5.6.14.zip', force: 'yes' }

- name: Create Elasticsearch Systemd Override Directory
  file:
    path: /etc/systemd/system/elasticsearch.service.d/
    state: directory
    owner: root
    group: root

- name: Install Elasticsearch systemd override
  copy:
    src: roles/es-data/files/elasticsearch.service.d/override.conf
    dest: /etc/systemd/system/elasticsearch.service.d/override.conf
    owner: root
    group: root
    mode: 0644

- name: Create Directories
  file:
    path: /data/elasticsearch
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0750

- name: Elasticsearch Configurations
  template: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
    - { src: 'roles/es-data/templates/elasticsearch.yml.template', dest: '/etc/elasticsearch/elasticsearch.yml', owner: 'elasticsearch', group: 'elasticsearch', mode: '0644' }
    - { src: 'roles/es-data/templates/jvm.options.template', dest: '/etc/elasticsearch/jvm.options', owner: 'elasticsearch', group: 'elasticsearch', mode: '0644' }
    - { src: 'roles/es-master/templates/x-pack/log4j2.properties.template', dest: '/etc/elasticsearch/x-pack/log4j2.properties', owner: 'elasticsearch', group: 'elasticsearch', mode: '0644' }


- name: Set PAM Limits
  pam_limits: domain={{ item.domain }} limit_type={{ item.limit_type }} limit_item={{ item.limit_item }} value={{ item.value }}
  with_items: 
    - { domain: 'elasticsearch', limit_type: 'soft', limit_item: 'memlock', value: 'unlimited' }
    - { domain: 'elasticsearch', limit_type: 'hard', limit_item: 'memlock', value: 'unlimited' }
    - { domain: 'elasticsearch', limit_type: 'soft', limit_item: 'nproc', value: '2048' }
    - { domain: 'elasticsearch', limit_type: 'hard', limit_item: 'nproc', value: '2048' }
    - { domain: 'elasticsearch', limit_type: 'soft', limit_item: 'nofile', value: '65535' }
    - { domain: 'elasticsearch', limit_type: 'hard', limit_item: 'nofile', value: '65535' }

# Enable Services. 
- name: Enable Elasticsearch Service
  systemd: 
    name: elasticsearch
    enabled: yes
    masked: no
    state: restarted
